{% set name = "ctk-cli" %}
{% set version = "1.4" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "80bad5eae3ce0d1ece63b53dd2c3dbe4b0bb7f6a18d13748866ae09c83b844b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - ctk_cli

about:
  home: https://github.com/commontk/ctk-cli
  license_file: LICENSE_Apache_20
  license: Apache 2.0
  license_family: Apache
  summary: Python interface for inspecting and running CLI modules (as defined by CommonTK)
  dev_url: https://github.com/commontk/ctk-cli
  doc_url: https://ctk-cli.readthedocs.io


extra:
  recipe-maintainers:
    - pmlandwehr
