{% set name = "ctk-cli" %}
{% set version = "1.5" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "63afcf2826d867e608f1542db7493a23466e49b7a7ed611e0f098dae33404645" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv .

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - ctk_cli

about:
  home: https://github.com/commontk/ctk-cli
  # No manifest - see https://github.com/commontk/ctk-cli/pull/16
  # Filler copy as patch:
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE_Apache_20'
  license: Apache 2.0
  license_family: Apache
  summary: Python interface for inspecting and running CLI modules (as defined by CommonTK)
  dev_url: https://github.com/commontk/ctk-cli
  doc_url: https://ctk-cli.readthedocs.io


extra:
  recipe-maintainers:
    - pmlandwehr
