travis:
  secure:
    BINSTAR_TOKEN: Wyof5DDE7uovgrt49ySlUaxzmzWoxP2yTYOIbviPWy+p5D4R0VWIWqZSNG6DpyaKYx3gCaa2wUFnc+Uexm6I6fNPaQm6c03NmseO7e11uwuNmiwmezf2u4+HEuzibaMYTTWbwK+lE/pxxTW3bdE477gpsiwhaZDpgtbzl4FkA+dX3E/5vnqcAsfDAvkPyWLIXC1J3ok0JvTkOKbiGJwmYCUcphCfSGkRo2/3O3j2vQ+8Xfm7Zi46F3H4UZzYDcClZDA1dy89s09+kr3lOcSWbSDn0yf6K1iluWkjIv1/qHGDmKS1/1AdaXXABwv2mjhMlESkV+CnuJ+UX9F4KXrq+ch5plP6NBrazfyQp3F0YsyYgboBqyKm9Jpt8EALkVkErzuorVfHacTo+uHFt/bNQq9OAm+J/JLXX0/GWdkgL0jKKuafZjMTgCPboiQb81/g6QDGIF7ahaBRSwmWBrX/7zrEkVO29a/q4vRhJ4qI3s28p8buF3D8U9YfIWxCA9kgi1WqddZgzVbg1G2AzizOLu7u8SaWziSwvgfaaDeVXUDaDW1i+8z7L8sTW3H6Srv6tRfvWCLKfBX3LQNU/c/JJHU1ZhPb8hd2wUs/QZBw3pTDrMQng8ceGAqQbjb0U87f4l4iKTsyd+e68PIH1PnygJmRvL4R1E0ulhLO2bYb49E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
