travis:
  secure:
    BINSTAR_TOKEN: rpwZeqARkIQ8IjLRjuX8sVuwFh9/CpB6EhExqgCxyuPAt9NqKIf3AGT1MrXh2ZyM8Lfsv681Z8nZTwuV/jM7WEd1PaAQwOWZ3ag8hEMlEUYpnuXYG/l+1bRPOl07bc6HfBVwWuTC1XU7hMNBDftMGdu3iCsu0eX+iOqnzvVc+mOhg9Z0quhgVGzYPyxb+9sra5wdSPielWOk/Djs5QXyOcjB14LjC7u4HrrQegL87QL6xe7E7Bjcj2AJVui04j8naK2/+XlDnXgpw7ht/yQhNQ1gKWWfPNaxMc8idbfk9bq2NCKc4ZlA3DxEb7TzwHh2xEU7E+bT7d5ajdbf7qoa5VxIhbaK0O1z1UM/I0XHgnB7oZmlb6CeRVpufUOLXgZ8xOv+6Wkm/Vc6QASFNC2ac7HK5eWYognM+Gg8K17duE6pZApWmUm92eZuGBmBAlJPG8zeRt7Qba07tWOABU4f2oaYkSFZy9WmiKQqNnDNe56wTQXpPj6ipi+iTjftQC1kr/r0Bu7fJPOO9Oz80ddiur9Q4NrHSHYGXmjWKfbdt7wsMSqL7djTXwHBsMo2wvGpWoua3ByRS1E43CfhpXnJrvPRyx7kM8gZCW5NiO06IJ9zHlAP/seDUFPXk/VXkeZ3gzaFDJiyAgMOPq5HWqSX2gR333jr+IuGHxPIYJcBoH8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
